---
openapi: 3.0.0
info:
  title: Vend API Postman Collection
  description: |-
    We use Broker's own account on Unity to perform these tests on the TEST server.
    Please update the Basic Auth value since it may have been modified.
  contact: []
  version: "1.0"
servers:
- url: https://api.hubtel.com/vend
  variables: []
- url: http://localhost:7734/payments
  variables: []
paths:
  /airtime:
    post:
      summary: Airtime
      description: ""
      operationId: Airtime
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirtimeRequest'
            example:
              phone: 0249441409
              amount: 1
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              network: 62001
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /surfline:
    post:
      summary: Surfline
      description: this is for buying surfline bundles
      operationId: Surfline
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurflineRequest'
            example:
              device: 233255000100
              amount: 25
              bundle: 1gbolddata
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
    get:
      summary: Surfline Query
      description: This is for querying details about a surfline number
      operationId: SurflineQuery
      parameters:
      - name: device
        in: query
        description: ""
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
          example: 233255000102
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /surflineplus:
    post:
      summary: SurflinePlus Payment
      description: ""
      operationId: SurflineplusPayment
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurflinePlusPaymentRequest'
            example:
              device: 233255000102
              amount: 9.900000
              bundle: 0.5gbnewdata
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /mobilemoney:
    post:
      summary: Mobile Money
      description: |-
        This is for sending funds to a mobile money wallet.
        Please ensure that the receiverPhone field is a valid mobile money number
      operationId: MobileMoney
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MobileMoneyRequest'
            example:
              receiverPhone: 0549436471
              receiverName: Daniel Opuni
              amount: 1
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              provider: MTN
              sender: Broker
              callbackUrl: http://apps.smsgh.com/broker/callback
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /dstv:
    post:
      summary: DStv Payment
      description: This is for paying DStv bill
      operationId: DstvPayment
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DStvPaymentRequest'
            example:
              account: 2022375158
              amount: 45
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              foreignId: 456345jfghnfdfrt4
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
    get:
      summary: DSTV Query
      description: ""
      operationId: DstvQuery
      parameters:
      - name: account
        in: query
        description: ""
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 2022375158
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /gotv:
    post:
      summary: GOtv Payment
      description: This is for paying GOtv bill
      operationId: GotvPayment
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GOtvPaymentRequest'
            example:
              account: 2022375158
              amount: 45
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              foreignId: 456345jfghnfdfrt4
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
    get:
      summary: GOtv Query
      description: ""
      operationId: GotvQuery
      parameters:
      - name: account
        in: query
        description: ""
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 2022375158
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /vodafone:
    post:
      summary: Vodafone Postpaid
      description: ""
      operationId: VodafonePostpaid
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VodafonePostpaidRequest'
            example:
              account: 11776577
              service: postpaid
              amount: 1
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              foreignId: 456345jfghnfdfrt4
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
    get:
      summary: Vodafone Query
      description: This is for querying vodafone broadband or postpaid account details
      operationId: VodafoneQuery
      parameters:
      - name: account
        in: query
        description: ""
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 50931149
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /busy:
    post:
      summary: BUSY4G Payment
      description: ""
      operationId: Busy4gPayment
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BUSY4GPaymentRequest'
            example:
              account: 233000122
              amount: 3
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              bundle: 701
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
    get:
      summary: BUSY4G Query
      description: This is for querying details about a Busy4G number
      operationId: Busy4gQuery
      parameters:
      - name: account
        in: query
        description: ""
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 233000122
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: http://localhost:7734/payments
        variables: []
  /mtn:
    post:
      summary: MTN Postpaid
      description: ""
      operationId: MtnPostpaid
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MTNPostpaidRequest'
            example:
              phone: 0249441409
              amount: 1
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              service: postpaid
              foreignId: 456345jfghnfdfrt4
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /ecg:
    post:
      summary: ECG Postpaid
      description: this is for paying for ECG postpaid bill
      operationId: EcgPostpaid
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ECGPostpaidRequest'
            example:
              account: 123434342324234
              amount: 25
              name: Kwaku Manu
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              foreignId: 456345jfghnfdfrt4
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /tvlicense:
    post:
      summary: TV License - Ghana Only
      description: This is for paying TV License bill
      operationId: Tv license  ghana only
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: string
              example: |-
                {
                  "account":"2022375158",
                  "amount":"1",
                  "token":"c81f1a54-2431-48d6-8772-ee9aa300d063".
                   "foreignId": "456345jfghnfdfrt4"
                }
            example: |-
              {
                "account":"2022375158",
                "amount":"1",
                "token":"c81f1a54-2431-48d6-8772-ee9aa300d063".
                 "foreignId": "456345jfghnfdfrt4"
              }
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /metadata/airtime:
    post:
      summary: Metadata - Airtime
      description: This will retrieve charges to be applied on a particular request
        (in this case, airtime). Replace "airtime" with any other service name, and
        modify the request payload
      operationId: Metadata  airtime
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata-AirtimeRequest'
            example:
              phone: 0249441409
              amount: 1
              token: c81f1a54-2431-48d6-8772-ee9aa300d063
              network: 62001
              foreignId: 456345jfghnfdfrt4
        required: true
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /balance/c81f1a54-2431-48d6-8772-ee9aa300d063:
    get:
      summary: Vend Balance
      description: check a wallet's balance
      operationId: VendBalance
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /transactions/6c25fbca-a5c3-48b3-8e2d-5a2118671893:
    get:
      summary: Query Transaction
      description: This is for querying details of a Broker transaction
      operationId: QueryTransaction
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
  /services:
    get:
      summary: Vend Services
      description: this retrieves all Broker services
      operationId: VendServices
      parameters:
      - name: Accept
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: ""
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ""
          headers: []
      deprecated: false
      servers:
      - url: https://api.hubtel.com/vend
        variables: []
components:
  schemas:
    AirtimeRequest:
      title: AirtimeRequest
      required:
      - phone
      - amount
      - token
      - network
      type: object
      properties:
        phone:
          type: string
        amount:
          type: string
        token:
          type: string
        network:
          type: string
      example:
        phone: 0249441409
        amount: 1
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        network: 62001
    SurflineRequest:
      title: SurflineRequest
      required:
      - device
      - amount
      - bundle
      - token
      type: object
      properties:
        device:
          type: string
        amount:
          type: string
        bundle:
          type: string
        token:
          type: string
      example:
        device: 233255000100
        amount: 25
        bundle: 1gbolddata
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
    SurflinePlusPaymentRequest:
      title: SurflinePlusPaymentRequest
      required:
      - device
      - amount
      - bundle
      - token
      type: object
      properties:
        device:
          type: string
        amount:
          type: string
        bundle:
          type: string
        token:
          type: string
      example:
        device: 233255000102
        amount: 9.900000
        bundle: 0.5gbnewdata
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
    MobileMoneyRequest:
      title: MobileMoneyRequest
      required:
      - receiverPhone
      - receiverName
      - amount
      - token
      - provider
      - sender
      - callbackUrl
      type: object
      properties:
        receiverPhone:
          type: string
        receiverName:
          type: string
        amount:
          type: integer
          format: int32
        token:
          type: string
        provider:
          type: string
        sender:
          type: string
        callbackUrl:
          type: string
      example:
        receiverPhone: 0549436471
        receiverName: Daniel Opuni
        amount: 1
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        provider: MTN
        sender: Broker
        callbackUrl: http://apps.smsgh.com/broker/callback
    DStvPaymentRequest:
      title: DStvPaymentRequest
      required:
      - account
      - amount
      - token
      - foreignId
      type: object
      properties:
        account:
          type: string
        amount:
          type: string
        token:
          type: string
        foreignId:
          type: string
      example:
        account: 2022375158
        amount: 45
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        foreignId: 456345jfghnfdfrt4
    GOtvPaymentRequest:
      title: GOtvPaymentRequest
      required:
      - account
      - amount
      - token
      - foreignId
      type: object
      properties:
        account:
          type: string
        amount:
          type: string
        token:
          type: string
        foreignId:
          type: string
      example:
        account: 2022375158
        amount: 45
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        foreignId: 456345jfghnfdfrt4
    VodafonePostpaidRequest:
      title: VodafonePostpaidRequest
      required:
      - account
      - service
      - amount
      - token
      - foreignId
      type: object
      properties:
        account:
          type: string
        service:
          type: string
        amount:
          type: string
        token:
          type: string
        foreignId:
          type: string
      example:
        account: 11776577
        service: postpaid
        amount: 1
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        foreignId: 456345jfghnfdfrt4
    BUSY4GPaymentRequest:
      title: BUSY4GPaymentRequest
      required:
      - account
      - amount
      - token
      - bundle
      type: object
      properties:
        account:
          type: string
        amount:
          type: string
        token:
          type: string
        bundle:
          type: string
      example:
        account: 233000122
        amount: 3
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        bundle: 701
    MTNPostpaidRequest:
      title: MTNPostpaidRequest
      required:
      - phone
      - amount
      - token
      - service
      - foreignId
      type: object
      properties:
        phone:
          type: string
        amount:
          type: string
        token:
          type: string
        service:
          type: string
        foreignId:
          type: string
      example:
        phone: 0249441409
        amount: 1
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        service: postpaid
        foreignId: 456345jfghnfdfrt4
    ECGPostpaidRequest:
      title: ECGPostpaidRequest
      required:
      - account
      - amount
      - name
      - token
      - foreignId
      type: object
      properties:
        account:
          type: string
        amount:
          type: string
        name:
          type: string
        token:
          type: string
        foreignId:
          type: string
      example:
        account: 123434342324234
        amount: 25
        name: Kwaku Manu
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        foreignId: 456345jfghnfdfrt4
    Metadata-AirtimeRequest:
      title: Metadata-AirtimeRequest
      required:
      - phone
      - amount
      - token
      - network
      - foreignId
      type: object
      properties:
        phone:
          type: string
        amount:
          type: string
        token:
          type: string
        network:
          type: string
        foreignId:
          type: string
      example:
        phone: 0249441409
        amount: 1
        token: c81f1a54-2431-48d6-8772-ee9aa300d063
        network: 62001
        foreignId: 456345jfghnfdfrt4
  securitySchemes:
    httpBasic:
      type: http
      scheme: basic
security:
- httpBasic: []
tags: []
...
