---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":6:{s:7:\"version\";s:5:\"0.0.1\";s:5:\"title\";s:27:\"OmniRule
  Authoring Services\";s:11:\"description\";s:57:\"Generate OmniRule RuleSets from
  Authored JSON definitions\";s:14:\"termsOfService\";s:25:\"https://omnirule.io/terms\";s:7:\"contact\";O:8:\"stdClass\":1:{s:4:\"name\";s:17:\"Herman
  Geldenhuys\";}s:7:\"license\";O:8:\"stdClass\":1:{s:4:\"name\";s:3:\"MIT\";}}"
basePath: /api
paths:
  /generate/table/multi-axis:
    post:
      description: Generate a Multi-Axis Decision Table
      operationId: multiAxisDecisionTable
      tags:
      - Generate Ruleset
      produces:
      - application/json
      parameters:
      - name: Multi Axis Decision Table JSON
        in: body
        description: 'Eligibility: A simple implementation of IMultiAxisDecisionTable'
        required: true
        schema:
          $ref: '#/definitions/MultiAxisTable'
      responses:
        200:
          description: RuleSet
          schema:
            type: object
            example:
              rules:
              - name: Rule1
                code: Some JS Code
                behaviour: Normal
              Version: 0.0.0.draft
              Id: RuleSet
              SchemaVersion: b6f12be0f14ca67608f7fc2f7520a8f2
              error: []
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /generate/table/single-axis:
    post:
      description: Generate a Single-Axis Decision Table
      operationId: SingleAxisDecisionTable
      tags:
      - Generate Ruleset
      produces:
      - application/json
      parameters:
      - name: Single Axis Decision Table JSON
        in: body
        description: tags to filter by
        required: true
        schema:
          $ref: '#/definitions/SingleAxisTable'
      responses:
        200:
          description: RuleSet
          schema:
            type: object
            example:
              rules:
              - name: Rule1
                code: Some JS Code
                behaviour: Normal
              Version: 0.0.0.draft
              Id: RuleSet
              SchemaVersion: b6f12be0f14ca67608f7fc2f7520a8f2
              error: []
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /generate/ruleset:
    post:
      description: Generate a Ruleset
      operationId: ruleset
      tags:
      - Generate Ruleset
      produces:
      - application/json
      parameters:
      - name: Rule Set JSON
        in: body
        description: tags to filter by
        required: true
        schema:
          $ref: '#/definitions/RuleSet'
      responses:
        200:
          description: RuleSet
          schema:
            type: object
            example:
              rules:
              - name: Rule1
                code: Some JS Code
                behaviour: Normal
              Version: 0.0.0.draft
              Id: RuleSet
              SchemaVersion: b6f12be0f14ca67608f7fc2f7520a8f2
              error: []
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /load/engine:
    post:
      description: Load a Rules Engine Artifact
      operationId: loadEngine
      tags:
      - Run Rule Engines
      produces:
      - application/json
      parameters:
      - name: Engine
        in: body
        description: A rules engine
        required: true
        schema:
          $ref: '#/definitions/RuleArtifact'
      responses:
        200:
          description: Loaded Response
          schema:
            type: object
            example:
              loaded: true
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
  /run/engine:
    post:
      description: Run a Rules Engine Artifact
      operationId: runEngine
      tags:
      - Run Rule Engines
      produces:
      - application/json
      parameters:
      - name: BOM
        in: body
        description: Business Object Model (Schema)
        required: true
        schema:
          type: object
          example:
            bom:
              TotalSales: 1000000
              TotalAssets: 500000
              AccountReceivable: 10
              Inventory: 4000
              AccountsPayable: 15
              Purchases: 5
              CostOfGoodsSold: 5000
              SchemaVersion: "1"
            name: Activity
            version: 2.1.0.draft
      responses:
        200:
          description: Business Object Model (BOM) Result
          schema:
            type: object
            example:
              SomeAttribute: SomeValue
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
produces:
- application/json
schemes:
- http
- https
definitions: !php/object "O:8:\"stdClass\":11:{s:14:\"MultiAxisTable\";O:8:\"stdClass\":3:{s:7:\"example\";O:8:\"stdClass\":9:{s:6:\"inputs\";a:2:{i:0;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:3:\"Age\";s:5:\"label\";s:3:\"Age\";s:12:\"relativePath\";s:3:\"Age\";}i:1;O:8:\"stdClass\":4:{s:8:\"dataType\";s:15:\"EnumerationType\";s:5:\"token\";s:6:\"Gender\";s:5:\"label\";s:6:\"Gender\";s:12:\"relativePath\";s:6:\"Gender\";}}s:7:\"outputs\";a:1:{i:0;O:8:\"stdClass\":6:{s:8:\"dataType\";s:11:\"BooleanType\";s:11:\"calculation\";s:9:\"undefined\";s:5:\"token\";s:8:\"Eligible\";s:12:\"relativePath\";s:8:\"Eligible\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:5:\"false\";}}s:7:\"version\";s:11:\"0.2.0.draft\";s:11:\"ruleContext\";O:8:\"stdClass\":2:{s:4:\"name\";s:22:\"noun_Coffee_472911.png\";s:12:\"enumerations\";a:1:{i:0;O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Gender\";s:6:\"values\";a:2:{i:0;O:8:\"stdClass\":1:{s:5:\"value\";s:4:\"Male\";}i:1;O:8:\"stdClass\":1:{s:5:\"value\";s:6:\"Female\";}}}}}s:4:\"name\";s:5:\"OfAge\";s:18:\"decisionObjectType\";s:13:\"DecisionTable\";s:5:\"cells\";a:6:{i:0;O:8:\"stdClass\":3:{s:12:\"columnNumber\";i:1;s:9:\"rowNumber\";i:1;s:7:\"outputs\";a:0:{}}i:1;O:8:\"stdClass\":3:{s:12:\"columnNumber\";i:1;s:9:\"rowNumber\";i:2;s:7:\"outputs\";a:0:{}}i:2;O:8:\"stdClass\":3:{s:12:\"columnNumber\";i:2;s:9:\"rowNumber\";i:1;s:7:\"outputs\";a:1:{i:0;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"BooleanType\";s:5:\"token\";s:8:\"Eligible\";s:11:\"calculation\";s:4:\"true\";s:6:\"active\";b:1;}}}i:3;O:8:\"stdClass\":3:{s:12:\"columnNumber\";i:2;s:9:\"rowNumber\";i:2;s:7:\"outputs\";a:1:{i:0;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"BooleanType\";s:5:\"token\";s:8:\"Eligible\";s:11:\"calculation\";s:5:\"false\";s:6:\"active\";b:1;}}}i:4;O:8:\"stdClass\":3:{s:12:\"columnNumber\";i:3;s:9:\"rowNumber\";i:1;s:7:\"outputs\";a:0:{}}i:5;O:8:\"stdClass\":3:{s:12:\"columnNumber\";i:3;s:9:\"rowNumber\";i:2;s:7:\"outputs\";a:0:{}}}s:7:\"columns\";a:3:{i:0;O:8:\"stdClass\":4:{s:7:\"outputs\";a:1:{i:0;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"BooleanType\";s:5:\"token\";s:8:\"Eligible\";s:11:\"calculation\";s:5:\"false\";s:6:\"active\";b:1;}}s:10:\"conditions\";a:1:{i:0;O:8:\"stdClass\":4:{s:10:\"expression\";s:8:\"Age
  < 19\";s:13:\"conditionType\";s:18:\"Boolean_Expression\";s:5:\"label\";s:8:\"Age
  < 19\";s:5:\"index\";i:1;}}s:4:\"name\";s:15:\"Younger than 19\";s:5:\"index\";i:1;}i:1;O:8:\"stdClass\":5:{s:4:\"guid\";s:16:\"6755399441059846\";s:7:\"outputs\";a:0:{}s:10:\"conditions\";a:1:{i:0;O:8:\"stdClass\":4:{s:10:\"expression\";s:24:\"(18
  < Age) && (Age < 21)\";s:13:\"conditionType\";s:18:\"Boolean_Expression\";s:5:\"label\";s:13:\"18
  < Age < 21\";s:5:\"index\";i:1;}}s:4:\"name\";s:5:\"19-20\";s:5:\"index\";i:2;}i:2;O:8:\"stdClass\":5:{s:4:\"guid\";s:16:\"6755399441060245\";s:7:\"outputs\";a:1:{i:0;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"BooleanType\";s:5:\"token\";s:8:\"Eligible\";s:11:\"calculation\";s:4:\"true\";s:6:\"active\";b:1;}}s:10:\"conditions\";a:1:{i:0;O:8:\"stdClass\":4:{s:10:\"expression\";s:8:\"Age
  > 20\";s:13:\"conditionType\";s:18:\"Boolean_Expression\";s:5:\"label\";s:8:\"Age
  > 20\";s:5:\"index\";i:1;}}s:4:\"name\";s:13:\"Older than 20\";s:5:\"index\";i:3;}}s:4:\"rows\";a:2:{i:0;O:8:\"stdClass\":5:{s:4:\"guid\";s:17:\"14073748835536702\";s:7:\"outputs\";a:1:{i:0;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"BooleanType\";s:5:\"token\";s:8:\"Eligible\";s:11:\"calculation\";s:4:\"true\";s:6:\"active\";b:1;}}s:10:\"conditions\";a:1:{i:0;O:8:\"stdClass\":4:{s:10:\"expression\";s:19:\"Gender
  === 'Female'\";s:13:\"conditionType\";s:18:\"Boolean_Expression\";s:5:\"label\";s:19:\"Gender
  === 'Female'\";s:5:\"index\";i:1;}}s:4:\"name\";s:5:\"Women\";s:5:\"index\";i:1;}i:1;O:8:\"stdClass\":4:{s:7:\"outputs\";a:0:{}s:10:\"conditions\";a:1:{i:0;O:8:\"stdClass\":5:{s:10:\"expression\";s:17:\"Gender
  === 'Male'\";s:13:\"conditionType\";s:18:\"Boolean_Expression\";s:5:\"label\";s:17:\"Gender
  === 'Male'\";s:4:\"guid\";s:17:\"17169973579351820\";s:5:\"index\";i:1;}}s:4:\"name\";s:3:\"Men\";s:5:\"index\";i:2;}}}s:4:\"type\";s:6:\"object\";s:10:\"properties\";O:8:\"stdClass\":6:{s:7:\"columns\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:18:\"#/definitions/Axis\";}}s:4:\"rows\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:18:\"#/definitions/Axis\";}}s:5:\"cells\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:18:\"#/definitions/Cell\";}}s:6:\"inputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:19:\"#/definitions/Input\";}}s:7:\"outputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:20:\"#/definitions/Output\";}}s:7:\"purpose\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}}s:15:\"SingleAxisTable\";O:8:\"stdClass\":3:{s:7:\"example\";O:8:\"stdClass\":9:{s:7:\"entries\";a:2:{i:0;O:8:\"stdClass\":3:{s:4:\"name\";s:0:\"\";s:7:\"outputs\";a:2:{i:0;O:8:\"stdClass\":2:{s:5:\"token\";s:11:\"SeatUpgrade\";s:11:\"calculation\";s:10:\"'Approved'\";}i:1;O:8:\"stdClass\":2:{s:5:\"token\";s:6:\"Points\";s:11:\"calculation\";s:3:\"100\";}}s:10:\"conditions\";a:2:{i:0;O:8:\"stdClass\":3:{s:5:\"token\";s:5:\"Level\";s:10:\"expression\";s:11:\"'Executive'\";s:13:\"conditionType\";s:7:\"Boolean\";}i:1;O:8:\"stdClass\":3:{s:5:\"token\";s:12:\"FlightStatus\";s:10:\"expression\";s:15:\"'International'\";s:13:\"conditionType\";s:7:\"Boolean\";}}}i:1;O:8:\"stdClass\":3:{s:4:\"name\";s:0:\"\";s:7:\"outputs\";a:2:{i:0;O:8:\"stdClass\":2:{s:5:\"token\";s:11:\"SeatUpgrade\";s:11:\"calculation\";s:14:\"'Not
  Approved'\";}i:1;O:8:\"stdClass\":2:{s:5:\"token\";s:6:\"Points\";s:11:\"calculation\";s:2:\"50\";}}s:10:\"conditions\";a:2:{i:0;O:8:\"stdClass\":3:{s:5:\"token\";s:5:\"Level\";s:10:\"expression\";s:9:\"'Manager'\";s:13:\"conditionType\";s:7:\"Boolean\";}i:1;O:8:\"stdClass\":3:{s:5:\"token\";s:12:\"FlightStatus\";s:10:\"expression\";s:15:\"'International'\";s:13:\"conditionType\";s:7:\"Boolean\";}}}}s:7:\"version\";s:1:\"1\";s:11:\"ruleContext\";O:8:\"stdClass\":2:{s:4:\"name\";s:7:\"Testing\";s:12:\"enumerations\";a:2:{i:0;O:8:\"stdClass\":2:{s:4:\"name\";s:5:\"Level\";s:6:\"values\";a:2:{i:0;O:8:\"stdClass\":1:{s:5:\"value\";s:9:\"Executive\";}i:1;O:8:\"stdClass\":1:{s:5:\"value\";s:7:\"Manager\";}}}i:1;O:8:\"stdClass\":2:{s:4:\"name\";s:12:\"FlightStatus\";s:6:\"values\";a:2:{i:0;O:8:\"stdClass\":1:{s:5:\"value\";s:13:\"International\";}i:1;O:8:\"stdClass\":1:{s:5:\"value\";s:8:\"Domestic\";}}}}}s:4:\"name\";s:6:\"VTable\";s:6:\"inputs\";a:2:{i:0;O:8:\"stdClass\":4:{s:5:\"token\";s:5:\"Level\";s:8:\"dataType\";s:4:\"Enum\";s:14:\"enumerationSet\";s:5:\"Level\";s:9:\"mockValue\";s:11:\"'Executive'\";}i:1;O:8:\"stdClass\":4:{s:5:\"token\";s:12:\"FlightStatus\";s:8:\"dataType\";s:4:\"Enum\";s:14:\"enumerationSet\";s:12:\"FlightStatus\";s:9:\"mockValue\";s:15:\"'International'\";}}s:7:\"outputs\";a:2:{i:0;O:8:\"stdClass\":1:{s:5:\"token\";s:11:\"SeatUpgrade\";}i:1;O:8:\"stdClass\":1:{s:5:\"token\";s:6:\"Points\";}}s:10:\"parentName\";s:0:\"\";s:18:\"decisionObjectType\";s:15:\"SingleAxisTable\";s:7:\"purpose\";s:0:\"\";}s:4:\"type\";s:6:\"object\";s:10:\"properties\";O:8:\"stdClass\":5:{s:7:\"entries\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:18:\"#/definitions/Axis\";}}s:6:\"inputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:19:\"#/definitions/Input\";}}s:7:\"outputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:20:\"#/definitions/Output\";}}s:10:\"conditions\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Condition\";}}s:7:\"purpose\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}}s:7:\"RuleSet\";O:8:\"stdClass\":3:{s:7:\"example\";O:8:\"stdClass\":6:{s:6:\"inputs\";a:7:{i:0;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:10:\"totalSales\";s:5:\"label\";s:11:\"Total
  Sales\";s:12:\"relativePath\";s:10:\"TotalSales\";}i:1;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:11:\"totalAssets\";s:5:\"label\";s:12:\"Total
  Assets\";s:12:\"relativePath\";s:11:\"TotalAssets\";}i:2;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:17:\"accountReceivable\";s:5:\"label\";s:18:\"Account
  Receivable\";s:12:\"relativePath\";s:17:\"AccountReceivable\";}i:3;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:9:\"inventory\";s:5:\"label\";s:9:\"Inventory\";s:12:\"relativePath\";s:9:\"Inventory\";}i:4;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:15:\"accountsPayable\";s:5:\"label\";s:16:\"Accounts
  Payable\";s:12:\"relativePath\";s:15:\"AccountsPayable\";}i:5;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:9:\"purchases\";s:5:\"label\";s:9:\"Purchases\";s:12:\"relativePath\";s:9:\"Purchases\";}i:6;O:8:\"stdClass\":4:{s:8:\"dataType\";s:11:\"DecimalType\";s:5:\"token\";s:15:\"costOfGoodsSold\";s:5:\"label\";s:18:\"Cost
  Of Goods Sold\";s:12:\"relativePath\";s:15:\"CostOfGoodsSold\";}}s:7:\"outputs\";a:7:{i:0;O:8:\"stdClass\":6:{s:8:\"dataType\";s:11:\"DecimalType\";s:11:\"calculation\";s:61:\"result
  = Math.round((totalSales / totalAssets) * 1000) / 1000\";s:5:\"token\";s:13:\"assetTurnover\";s:12:\"relativePath\";s:13:\"AssetTurnover\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:14:\"Asset
  Turnover\";}i:1;O:8:\"stdClass\":6:{s:8:\"dataType\";s:11:\"DecimalType\";s:11:\"calculation\";s:64:\"result
  = Math.round((costOfGoodsSold / inventory) * 1000) / 1000\";s:5:\"token\";s:17:\"inventoryTurnover\";s:12:\"relativePath\";s:17:\"InventoryTurnover\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:18:\"Inventory
  Turnover\";}i:2;O:8:\"stdClass\":6:{s:8:\"dataType\";s:11:\"DecimalType\";s:11:\"calculation\";s:61:\"result
  = Math.round(( 365 / inventoryTurnover) * 1000) / 1000\";s:5:\"token\";s:15:\"daysOnInventory\";s:12:\"relativePath\";s:15:\"DaysOnInventory\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:17:\"Days
  On Inventory\";}i:3;O:8:\"stdClass\":7:{s:8:\"dataType\";s:11:\"DecimalType\";s:11:\"calculation\";s:72:\"result
  = Math.round(((accountsPayable / purchases) * 365) * 1000) / 1000\";s:5:\"token\";s:15:\"aPPaymentPeriod\";s:12:\"relativePath\";s:15:\"aPPaymentPeriod\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:18:\"A/P
  Payment Period\";s:13:\"ruleBehaviour\";s:18:\"Require_All_Inputs\";}i:4;O:8:\"stdClass\":7:{s:8:\"dataType\";s:11:\"DecimalType\";s:11:\"calculation\";s:75:\"result
  = Math.round(((accountReceivable / totalSales) * 365) * 1000) / 1000\";s:5:\"token\";s:18:\"aRCollectionPeriod\";s:12:\"relativePath\";s:18:\"ARCollectionPeriod\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:21:\"A/R
  Collection Period\";s:13:\"ruleBehaviour\";s:18:\"Require_All_Inputs\";}i:5;O:8:\"stdClass\":6:{s:8:\"dataType\";s:11:\"DecimalType\";s:11:\"calculation\";s:67:\"result
  = Math.round((totalSales / accountReceivable) * 1000) / 1000\";s:5:\"token\";s:19:\"receivablesTurnover\";s:12:\"relativePath\";s:19:\"ReceivablesTurnover\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:20:\"Receivables
  Turnover\";}i:6;O:8:\"stdClass\":6:{s:8:\"dataType\";s:11:\"DecimalType\";s:11:\"calculation\";s:62:\"result
  = Math.round((365 / receivablesTurnover) * 1000) / 1000\";s:5:\"token\";s:22:\"daysOfSalesOutstanding\";s:12:\"relativePath\";s:22:\"DaysOfSalesOutstanding\";s:10:\"conditions\";a:0:{}s:5:\"label\";s:25:\"Days
  Of Sales Outstanding\";}}s:7:\"version\";s:11:\"2.1.0.draft\";s:11:\"ruleContext\";O:8:\"stdClass\":2:{s:4:\"name\";s:9:\"Image.svg\";s:12:\"enumerations\";a:0:{}}s:4:\"name\";s:8:\"Activity\";s:18:\"decisionObjectType\";s:7:\"RuleSet\";}s:4:\"type\";s:6:\"object\";s:10:\"properties\";O:8:\"stdClass\":3:{s:6:\"inputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:19:\"#/definitions/Input\";}}s:7:\"outputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:20:\"#/definitions/Output\";}}s:7:\"purpose\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}}s:4:\"Axis\";O:8:\"stdClass\":2:{s:4:\"type\";s:6:\"object\";s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":2:{s:8:\"required\";a:4:{i:0;s:4:\"name\";i:1;s:5:\"index\";i:2;s:7:\"outputs\";i:3;s:10:\"conditions\";}s:10:\"properties\";O:8:\"stdClass\":4:{s:4:\"name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:5:\"index\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:7:\"outputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:20:\"#/definitions/Output\";}}s:10:\"conditions\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:20:\"#/definitions/Output\";}}}}}}s:4:\"Cell\";O:8:\"stdClass\":2:{s:4:\"type\";s:6:\"object\";s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":2:{s:4:\"type\";s:6:\"object\";s:10:\"properties\";O:8:\"stdClass\":3:{s:12:\"columnNumber\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:9:\"rowNumber\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:7:\"outputs\";O:8:\"stdClass\":2:{s:4:\"type\";s:6:\"object\";s:4:\"$ref\";s:20:\"#/definitions/Output\";}}}}}s:6:\"Output\";O:8:\"stdClass\":2:{s:4:\"type\";s:6:\"object\";s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":2:{s:8:\"required\";a:3:{i:0;s:11:\"calculation\";i:1;s:8:\"dataType\";i:2;s:5:\"token\";}s:10:\"properties\";O:8:\"stdClass\":7:{s:5:\"token\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:11:\"calculation\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:8:\"rawValue\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:13:\"ruleBehaviour\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:5:\"label\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:8:\"dataType\";O:8:\"stdClass\":3:{s:4:\"type\";s:6:\"number\";s:4:\"enum\";a:9:{i:0;s:7:\"Unknown\";i:1;s:6:\"String\";i:2;s:7:\"Integer\";i:3;s:7:\"Boolean\";i:4;s:4:\"Date\";i:5;s:7:\"Decimal\";i:6;s:4:\"Enum\";i:7;s:4:\"List\";i:8;s:6:\"Object\";}s:7:\"default\";s:6:\"String\";}s:10:\"conditions\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Condition\";}}}}}}s:5:\"Input\";O:8:\"stdClass\":2:{s:4:\"type\";s:6:\"object\";s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":2:{s:8:\"required\";a:3:{i:0;s:8:\"rawValue\";i:1;s:8:\"dataType\";i:2;s:5:\"token\";}s:10:\"properties\";O:8:\"stdClass\":6:{s:5:\"token\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:8:\"rawValue\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:13:\"ruleBehaviour\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:5:\"label\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:8:\"dataType\";O:8:\"stdClass\":3:{s:4:\"type\";s:6:\"number\";s:4:\"enum\";a:9:{i:0;s:7:\"Unknown\";i:1;s:6:\"String\";i:2;s:7:\"Integer\";i:3;s:7:\"Boolean\";i:4;s:4:\"Date\";i:5;s:7:\"Decimal\";i:6;s:4:\"Enum\";i:7;s:4:\"List\";i:8;s:6:\"Object\";}s:7:\"default\";s:6:\"String\";}s:10:\"conditions\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Condition\";}}}}}}s:9:\"Condition\";O:8:\"stdClass\":2:{s:4:\"type\";s:6:\"object\";s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":2:{s:8:\"required\";a:5:{i:0;s:13:\"conditionType\";i:1;s:5:\"token\";i:2;s:11:\"calculation\";i:3;s:8:\"dataType\";i:4;s:11:\"calculation\";}s:10:\"properties\";O:8:\"stdClass\":11:{s:13:\"conditionType\";O:8:\"stdClass\":1:{s:4:\"type\";a:6:{i:0;i:0;i:1;i:1;i:2;i:2;i:3;i:3;i:4;i:4;i:5;i:5;}}s:11:\"calculation\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:10:\"expression\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:6:\"number\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:4:\"from\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:2:\"to\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:11:\"includeFrom\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"boolean\";}s:9:\"includeTo\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"boolean\";}s:5:\"token\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:5:\"label\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:5:\"index\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}}}}}s:10:\"ErrorModel\";O:8:\"stdClass\":3:{s:4:\"type\";s:6:\"object\";s:8:\"required\";a:2:{i:0;s:4:\"code\";i:1;s:7:\"message\";}s:10:\"properties\";O:8:\"stdClass\":2:{s:4:\"code\";O:8:\"stdClass\":2:{s:4:\"type\";s:7:\"integer\";s:6:\"format\";s:5:\"int32\";}s:7:\"message\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}}s:12:\"RuleArtifact\";O:8:\"stdClass\":4:{s:7:\"example\";O:8:\"stdClass\":5:{s:5:\"rules\";a:7:{i:0;O:8:\"stdClass\":3:{s:4:\"name\";s:13:\"AssetTurnover\";s:4:\"code\";s:96:\"var
  result = undefined;    result = Math.round((bom.TotalSales / bom.TotalAssets) *
  1000) / 1000\";s:9:\"behaviour\";s:6:\"Normal\";}i:1;O:8:\"stdClass\":3:{s:4:\"name\";s:17:\"InventoryTurnover\";s:4:\"code\";s:99:\"var
  result = undefined;    result = Math.round((bom.CostOfGoodsSold / bom.Inventory)
  * 1000) / 1000\";s:9:\"behaviour\";s:6:\"Normal\";}i:2;O:8:\"stdClass\":3:{s:4:\"name\";s:15:\"DaysOnInventory\";s:4:\"code\";s:91:\"var
  result = undefined;    result = Math.round((365 / bom.InventoryTurnover) * 1000)
  / 1000\";s:9:\"behaviour\";s:6:\"Normal\";}i:3;O:8:\"stdClass\":3:{s:4:\"name\";s:15:\"aPPaymentPeriod\";s:4:\"code\";s:107:\"var
  result = undefined;    result = Math.round(((bom.AccountsPayable / bom.Purchases)
  * 365) * 1000) / 1000\";s:9:\"behaviour\";s:6:\"Normal\";}i:4;O:8:\"stdClass\":3:{s:4:\"name\";s:18:\"ARCollectionPeriod\";s:4:\"code\";s:110:\"var
  result = undefined;    result = Math.round(((bom.AccountReceivable / bom.TotalSales)
  * 365) * 1000) / 1000\";s:9:\"behaviour\";s:6:\"Normal\";}i:5;O:8:\"stdClass\":3:{s:4:\"name\";s:19:\"ReceivablesTurnover\";s:4:\"code\";s:102:\"var
  result = undefined;    result = Math.round((bom.TotalSales / bom.AccountReceivable)
  * 1000) / 1000\";s:9:\"behaviour\";s:6:\"Normal\";}i:6;O:8:\"stdClass\":3:{s:4:\"name\";s:22:\"DaysOfSalesOutstanding\";s:4:\"code\";s:93:\"var
  result = undefined;    result = Math.round((365 / bom.ReceivablesTurnover) * 1000)
  / 1000\";s:9:\"behaviour\";s:6:\"Normal\";}}s:7:\"Version\";s:11:\"2.1.0.draft\";s:2:\"Id\";s:8:\"Activity\";s:13:\"SchemaVersion\";s:32:\"219b468a47bc7332df01ceba4d20cf56\";s:5:\"error\";O:8:\"stdClass\":0:{}}s:4:\"type\";s:6:\"object\";s:8:\"required\";a:4:{i:0;s:5:\"rules\";i:1;s:7:\"Version\";i:2;s:2:\"Id\";i:3;s:13:\"SchemaVersion\";}s:10:\"properties\";O:8:\"stdClass\":4:{s:5:\"rules\";O:8:\"stdClass\":2:{s:4:\"type\";s:5:\"array\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:18:\"#/definitions/Rule\";}}s:7:\"Version\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:2:\"Id\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:13:\"SchemaVersion\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}}s:4:\"Rule\";O:8:\"stdClass\":3:{s:4:\"type\";s:6:\"object\";s:8:\"required\";a:3:{i:0;s:4:\"name\";i:1;s:4:\"code\";i:2;s:9:\"behaviour\";}s:10:\"properties\";O:8:\"stdClass\":3:{s:4:\"name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:4:\"code\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:9:\"behaviour\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}}}"
...
