---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":10:{s:7:\"contact\";O:8:\"stdClass\":1:{s:9:\"x-twitter\";s:10:\"PersonioHR\";}s:11:\"description\";s:84:\"API
  for reading and writing personnel data incl. data about attendances and absences\";s:5:\"title\";s:14:\"Personnel
  Data\";s:7:\"version\";s:3:\"1.0\";s:21:\"x-apisguru-categories\";a:1:{i:0;s:10:\"enterprise\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:83:\"https://api.apis.guru/v2/cache/logo/https_twitter.com_PersonioHR_profile_image.jpeg\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":3:{s:6:\"format\";s:7:\"swagger\";s:3:\"url\";s:91:\"https://raw.githubusercontent.com/personio/api-docs/master/personio-personnel-data-api.yaml\";s:7:\"version\";s:3:\"2.0\";}}s:11:\"x-preferred\";b:1;s:14:\"x-providerName\";s:11:\"personio.de\";s:13:\"x-serviceName\";s:9:\"personnel\";}"
host: api.personio.de
basePath: /v1
paths:
  /company/attendances:
    get:
      description: This endpoint is responsible for fetching attendance data for the
        company employees. It is possible to paginate results, filter by period and/or
        specific employees. The result will contain a list of attendance periods,
        structured as defined here.
      parameters:
      - description: First day of the period to be queried. It is inclusive, so the
          day specified as start_date will also be considered on the results
        format: date
        in: query
        name: start_date
        required: true
        type: string
      - description: Last day of the period to be queried. It is inclusive, so the
          day specified as end_date will also be considered on the results.
        format: date
        in: query
        name: end_date
        required: true
        type: string
      - collectionFormat: multi
        description: A list of Personio employee identifiers to filter the results.
          Only those employees specified here will be returned.
        in: query
        items:
          type: integer
        name: employees
        required: false
        type: array
      - default: 200
        description: Pagination attribute to limit how many attendances will be returned
          per page
        in: query
        minimum: 1
        name: limit
        required: false
        type: integer
      - default: 0
        description: Pagination attribute to identify which page you are requesting,
          by the form of telling an offset from the first record that would be returned.
        in: query
        minimum: 0
        name: offset
        required: false
        type: integer
      responses:
        200:
          description: ""
          examples:
            application/json:
              data:
              - attributes:
                  break: 50
                  comment: I was productive as hell
                  date: "2017-01-17"
                  employee: 325659
                  end_time: "18:00"
                  is_holiday: false
                  is_on_time_off: false
                  start_time: "9:00"
                type: AttendancePeriod
              - attributes:
                  break: 60
                  date: "2017-01-18"
                  employee: 325660
                  end_time: "18:30"
                  is_holiday: false
                  is_on_time_off: true
                  start_time: "9:30"
                type: AttendancePeriod
              limit: 200
              offset: 0
              success: true
          schema:
            $ref: '#/definitions/AttendancePeriodsResponse'
    post:
      description: This endpoint is responsible for adding attendance data for the
        company employees. It is possible to add attendances for one or many employees
        at the same time. The payload sent on the request should be a list of attendance
        periods, in the form of an array containing attendance period objects.
      parameters:
      - description: List of attendance periods to create
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/NewAttendancePeriodRequest'
      responses:
        200:
          description: The attendance periods were created successfully
          examples:
            application/json:
              data:
                message: success
              success: true
          schema:
            $ref: '#/definitions/NewAttendancePeriodResponse'
        400:
          description: Invalid request
          examples:
            application/json:
              error:
                code: 400
                message: Error when trying to insert Attendances periods rows
              success: true
          schema:
            properties:
              error:
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                type: object
              success:
                type: boolean
            type: object
  /company/employees:
    get:
      description: List Employees
      parameters:
      - description: '[In development] Query string to perform search on. Returns
          all employees if not present. Can also be used with custom attributes, e.g.
          `dynamic_9382=abcd`'
        in: query
        name: query
        required: false
        type: string
      - description: '[In development] Attributes to be returend for employees found.
          Returns all available attributes if not present. Pass `attributes` multiple
          times of needed.'
        in: query
        items: []
        name: attributes
        required: false
        type: array
      responses:
        200:
          description: ""
          examples:
            application/json:
              data:
              - attributes:
                  contract_end_date:
                    label: Contract ends
                  cost_centers:
                    label: Cost center
                    value:
                    - attributes:
                        id: 320
                        name: Cost Center One
                        percentage: 50
                      type: CostCenter
                    - attributes:
                        id: 321
                        name: Cost Center Two
                        percentage: 50
                      type: CostCenter
                  created_at:
                    label: created_at
                    value: "2016-10-20T16:15:55+0200"
                  department:
                    label: Department
                    value:
                      attributes:
                        name: Marketing
                      type: Department
                  dynamic_21827:
                    label: IBAN
                    value: DE98 8989 9898 0000 8989 00
                  dynamic_24407:
                    label: Titel
                    value: Dr
                  email:
                    label: Email
                    value: andreas.anderson@demo.com
                  employment_type:
                    label: Employment type
                    value: internal
                  first_name:
                    label: First name
                    value: Andreas
                  fix_salary:
                    label: Fix salary
                    value: 4000
                  gender:
                    label: Gender
                    value: male
                  hire_date:
                    label: Hire date
                    value: "2012-02-01T00:00:00+0100"
                  hourly_salary:
                    label: Hourly salary
                    value: 0
                  id:
                    label: id
                    value: 83752
                  last_name:
                    label: Last name
                    value: Anderson
                  last_working_day:
                    label: Last working day
                    value: "2017-02-28T00:00:00+0200"
                  office:
                    label: Office
                    value:
                      attributes:
                        name: Munich
                      type: Office
                  position:
                    label: Position
                    value: Online Marketing Specialist
                  probation_period_end:
                    label: Probation period end
                    value: "2012-07-31T00:00:00+0200"
                  status:
                    label: Status
                    value: active
                  supervisor:
                    label: Supervisor
                    value:
                      attributes:
                        email:
                          label: Email
                          value: max.mustermann@example.org
                        first_name:
                          label: First name
                          value: Max
                        id:
                          label: id
                          value: 423506
                        last_name:
                          label: Last name
                          value: Mustermann
                      type: Employee
                  termination_date:
                    label: Termination date
                  termination_reason:
                    label: Termination reason
                    value: ""
                  termination_type:
                    label: Termination type
                    value: ""
                  vacation_day_balance:
                    label: Vacation day balance
                    value: 28.500000
                  weekly_working_hours:
                    label: Weekly hours
                    value: "40"
                type: Employee
              success: true
          schema:
            $ref: '#/definitions/EmployeesResponse'
  /company/employees/{employee_id}:
    get:
      description: Employee
      parameters:
      - description: Numeric `id` of the employee
        format: integer
        in: path
        name: employee_id
        required: true
        type: number
      responses:
        200:
          description: ""
          examples:
            application/json:
              data:
                attributes:
                  contract_end_date:
                    label: Contract ends
                  cost_centers:
                    label: Cost center
                    value:
                    - attributes:
                        id: 320
                        name: Cost Center One
                        percentage: 50
                      type: CostCenter
                    - attributes:
                        id: 321
                        name: Cost Center Two
                        percentage: 50
                      type: CostCenter
                  created_at:
                    label: created_at
                    value: "2016-10-20T16:15:55+0200"
                  department:
                    label: Department
                    value:
                      attributes:
                        name: Marketing
                      type: Department
                  dynamic_21827:
                    label: IBAN
                    value: DE98 8989 9898 0000 8989 00
                  dynamic_24407:
                    label: Titel
                    value: Dr
                  email:
                    label: Email
                    value: andreas.anderson@demo.com
                  employment_type:
                    label: Employment type
                    value: internal
                  first_name:
                    label: First name
                    value: Andreas
                  fix_salary:
                    label: Fix salary
                    value: 4000
                  gender:
                    label: Gender
                    value: male
                  hire_date:
                    label: Hire date
                    value: "2012-02-01T00:00:00+0100"
                  hourly_salary:
                    label: Hourly salary
                    value: 0
                  id:
                    label: id
                    value: 83752
                  last_name:
                    label: Last name
                    value: Anderson
                  last_working_day:
                    label: Last working day
                    value: "2017-02-28T00:00:00+0200"
                  office:
                    label: Office
                    value:
                      attributes:
                        name: Munich
                      type: Office
                  position:
                    label: Position
                    value: Online Marketing Specialist
                  probation_period_end:
                    label: Probation period end
                    value: "2012-07-31T00:00:00+0200"
                  status:
                    label: Status
                    value: active
                  supervisor:
                    label: Supervisor
                    value:
                      attributes:
                        email:
                          label: Email
                          value: max.mustermann@example.org
                        first_name:
                          label: First name
                          value: Max
                        id:
                          label: id
                          value: 423506
                        last_name:
                          label: Last name
                          value: Mustermann
                      type: Employee
                  termination_date:
                    label: Termination date
                  termination_reason:
                    label: Termination reason
                    value: ""
                  termination_type:
                    label: Termination type
                    value: ""
                  vacation_day_balance:
                    label: Vacation day balance
                    value: 28.500000
                  weekly_working_hours:
                    label: Weekly hours
                    value: "40"
                type: Employee
              success: true
          schema:
            $ref: '#/definitions/EmployeeResponse'
  /company/time-off/{time_off_id}:
    get:
      description: Absence Period
      parameters:
      - description: Numeric `id` of the absence period
        format: integer
        in: path
        name: time_off_id
        required: true
        type: number
      responses:
        200:
          description: ""
          examples:
            application/json:
              data:
                attributes:
                  certificate:
                    status: not-required
                  created_at: "2017-01-17T10:32:18+0100"
                  days_count: 3
                  employee:
                    attributes:
                      email:
                        label: Email
                        value: michael.miller@demo.com
                      first_name:
                        label: First name
                        value: Michael
                      last_name:
                        label: Last name
                        value: Miller
                    type: Employee
                  end_date: "2017-12-29T00:00:00+0100"
                  half_day_end: 0
                  half_day_start: 0
                  start_date: "2017-12-27T00:00:00+0100"
                  status: approved
                  time_off_type:
                    attributes:
                      name: Vacation
                    type: TimeOffType
                type: TimeOffPeriod
              success: true
          schema:
            $ref: '#/definitions/AbsencePeriodResponse'
  /company/time-offs:
    get:
      description: List All Absence Periods
      parameters: []
      responses:
        200:
          description: ""
          examples:
            application/json:
              data:
              - attributes:
                  certificate:
                    status: not-required
                  created_at: "2017-01-17T10:32:18+0100"
                  days_count: 3
                  employee:
                    attributes:
                      email:
                        label: Email
                        value: michael.miller@demo.com
                      first_name:
                        label: First name
                        value: Michael
                      last_name:
                        label: Last name
                        value: Miller
                    type: Employee
                  end_date: "2017-12-29T00:00:00+0100"
                  half_day_end: 0
                  half_day_start: 0
                  start_date: "2017-12-27T00:00:00+0100"
                  status: approved
                  time_off_type:
                    attributes:
                      name: Vacation
                    type: TimeOffType
                type: TimeOffPeriod
              success: true
          schema:
            $ref: '#/definitions/AbsencePeriodsResponse'
produces:
- application/json
schemes:
- https
definitions: !php/object "O:8:\"stdClass\":14:{s:21:\"AbsencePeriodResponse\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"object\";}s:22:\"AbsencePeriodsResponse\";O:8:\"stdClass\":3:{s:5:\"allOf\";a:2:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Response\";}i:1;O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:4:\"data\";O:8:\"stdClass\":3:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":10:{s:11:\"certificate\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:6:\"status\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}s:10:\"created_at\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:10:\"days_count\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:8:\"employee\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":3:{s:5:\"email\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:10:\"first_name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:9:\"last_name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}s:8:\"end_date\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:12:\"half_day_end\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:14:\"half_day_start\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:10:\"start_date\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:6:\"status\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:13:\"time_off_type\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:4:\"name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:8:\"required\";a:2:{i:0;s:4:\"type\";i:1;s:10:\"attributes\";}s:4:\"type\";s:6:\"object\";}}s:4:\"type\";s:6:\"object\";}}s:5:\"title\";s:33:\"List
  All Absence Periods response\";s:4:\"type\";s:6:\"object\";}s:25:\"AttendancePeriodsResponse\";O:8:\"stdClass\":3:{s:5:\"allOf\";a:2:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Response\";}i:1;O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":3:{s:4:\"data\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":3:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":3:{s:10:\"properties\";O:8:\"stdClass\":8:{s:5:\"break\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"integer\";}s:7:\"comment\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:4:\"date\";O:8:\"stdClass\":2:{s:6:\"format\";s:4:\"date\";s:4:\"type\";s:6:\"string\";}s:8:\"employee\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"integer\";}s:8:\"end_time\";O:8:\"stdClass\":2:{s:7:\"pattern\";s:11:\"^\\d\\d:\\d\\d$\";s:4:\"type\";s:6:\"string\";}s:10:\"is_holiday\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"boolean\";}s:14:\"is_on_time_off\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"boolean\";}s:10:\"start_time\";O:8:\"stdClass\":2:{s:7:\"pattern\";s:11:\"^\\d\\d:\\d\\d$\";s:4:\"type\";s:6:\"string\";}}s:8:\"required\";a:8:{i:0;s:8:\"employee\";i:1;s:4:\"date\";i:2;s:10:\"start_time\";i:3;s:8:\"end_time\";i:4;s:5:\"break\";i:5;s:7:\"comment\";i:6;s:10:\"is_holiday\";i:7;s:14:\"is_on_time_off\";}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:8:\"required\";a:2:{i:0;s:4:\"type\";i:1;s:10:\"attributes\";}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:5:\"limit\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"integer\";}s:6:\"offset\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"integer\";}}s:4:\"type\";s:6:\"object\";}}s:5:\"title\";s:35:\"List
  All Attenance Periods response\";s:4:\"type\";s:6:\"object\";}s:9:\"Attribute\";O:8:\"stdClass\":3:{s:10:\"properties\";O:8:\"stdClass\":2:{s:5:\"label\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:5:\"value\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"object\";}}s:8:\"required\";a:2:{i:0;s:5:\"label\";i:1;s:5:\"value\";}s:4:\"type\";s:6:\"object\";}s:11:\"CostCenters\";O:8:\"stdClass\":3:{s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}}s:10:\"properties\";O:8:\"stdClass\":1:{s:5:\"value\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":3:{s:2:\"id\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}s:4:\"name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}s:10:\"percentage\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"number\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}}s:4:\"type\";s:6:\"object\";}s:10:\"Department\";O:8:\"stdClass\":3:{s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}}s:10:\"properties\";O:8:\"stdClass\":1:{s:5:\"value\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:4:\"name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}}s:4:\"type\";s:6:\"object\";}s:8:\"Employee\";O:8:\"stdClass\":3:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":23:{s:17:\"contract_end_date\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:12:\"cost_centers\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:25:\"#/definitions/CostCenters\";}s:10:\"created_at\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:10:\"department\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:24:\"#/definitions/Department\";}s:5:\"email\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:15:\"employment_type\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:10:\"first_name\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:10:\"fix_salary\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:6:\"gender\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:9:\"hire_date\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:13:\"hourly_salary\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:2:\"id\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:9:\"last_name\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:6:\"office\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:20:\"#/definitions/Office\";}s:8:\"position\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:20:\"probation_period_end\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:6:\"status\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:10:\"supervisor\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:24:\"#/definitions/Supervisor\";}s:16:\"termination_date\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:18:\"termination_reason\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:16:\"termination_type\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:20:\"vacation_day_balance\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}s:20:\"weekly_working_hours\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:8:\"required\";a:2:{i:0;s:4:\"type\";i:1;s:10:\"attributes\";}s:4:\"type\";s:6:\"object\";}s:16:\"EmployeeResponse\";O:8:\"stdClass\":2:{s:5:\"allOf\";a:2:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Response\";}i:1;O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:4:\"data\";O:8:\"stdClass\":2:{s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Employee\";}}s:4:\"type\";s:6:\"object\";}}s:4:\"type\";s:6:\"object\";}}s:5:\"title\";s:8:\"Employee\";}s:17:\"EmployeesResponse\";O:8:\"stdClass\":2:{s:5:\"allOf\";a:2:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Response\";}i:1;O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:4:\"data\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Employee\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}}s:4:\"type\";s:6:\"object\";}}s:5:\"title\";s:17:\"List
  of Employees\";}s:26:\"NewAttendancePeriodRequest\";O:8:\"stdClass\":4:{s:7:\"example\";O:8:\"stdClass\":1:{s:11:\"attendances\";a:2:{i:0;O:8:\"stdClass\":5:{s:5:\"break\";i:120;s:4:\"date\";s:10:\"2017-01-18\";s:8:\"employee\";i:1234;s:8:\"end_time\";s:5:\"18:00\";s:10:\"start_time\";s:4:\"8:00\";}i:1;O:8:\"stdClass\":6:{s:5:\"break\";i:35;s:7:\"comment\";s:24:\"I
  was productive as hell\";s:4:\"date\";s:10:\"2017-01-17\";s:8:\"employee\";i:1235;s:8:\"end_time\";s:5:\"12:00\";s:10:\"start_time\";s:4:\"9:00\";}}}s:10:\"properties\";O:8:\"stdClass\":1:{s:11:\"attendances\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":3:{s:10:\"properties\";O:8:\"stdClass\":6:{s:5:\"break\";O:8:\"stdClass\":3:{s:11:\"description\";s:16:\"Break
  in minutes\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:7:\"comment\";O:8:\"stdClass\":2:{s:11:\"description\";s:16:\"Optional
  comment\";s:4:\"type\";s:6:\"string\";}s:4:\"date\";O:8:\"stdClass\":3:{s:11:\"description\";s:29:\"Attendance
  date as YYYY-MM-DD\";s:6:\"format\";s:4:\"date\";s:4:\"type\";s:6:\"string\";}s:8:\"employee\";O:8:\"stdClass\":2:{s:11:\"description\";s:19:\"Employee
  identifier\";s:4:\"type\";s:7:\"integer\";}s:8:\"end_time\";O:8:\"stdClass\":3:{s:11:\"description\";s:17:\"End
  time as HH:MM\";s:7:\"pattern\";s:11:\"^\\d\\d:\\d\\d$\";s:4:\"type\";s:6:\"string\";}s:10:\"start_time\";O:8:\"stdClass\":3:{s:11:\"description\";s:19:\"Start
  time as HH:MM\";s:7:\"pattern\";s:11:\"^\\d\\d:\\d\\d$\";s:4:\"type\";s:6:\"string\";}}s:8:\"required\";a:6:{i:0;s:8:\"employee\";i:1;s:4:\"date\";i:2;s:10:\"start_time\";i:3;s:8:\"end_time\";i:4;s:5:\"break\";i:5;s:7:\"comment\";}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}}s:5:\"title\";s:38:\"Create
  a New Attendance Period request\";s:4:\"type\";s:6:\"object\";}s:27:\"NewAttendancePeriodResponse\";O:8:\"stdClass\":2:{s:5:\"allOf\";a:2:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Response\";}i:1;O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:4:\"data\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:7:\"message\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}}s:4:\"type\";s:6:\"object\";}}s:4:\"type\";s:6:\"object\";}s:6:\"Office\";O:8:\"stdClass\":3:{s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}}s:10:\"properties\";O:8:\"stdClass\":1:{s:5:\"value\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":2:{s:10:\"attributes\";O:8:\"stdClass\":2:{s:5:\"items\";O:8:\"stdClass\":2:{s:10:\"properties\";O:8:\"stdClass\":1:{s:4:\"name\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}s:4:\"type\";s:5:\"array\";}s:4:\"type\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"string\";}}s:4:\"type\";s:6:\"object\";}}s:4:\"type\";s:6:\"object\";}s:8:\"Response\";O:8:\"stdClass\":4:{s:10:\"properties\";O:8:\"stdClass\":2:{s:4:\"data\";O:8:\"stdClass\":1:{s:4:\"type\";s:6:\"object\";}s:7:\"success\";O:8:\"stdClass\":1:{s:4:\"type\";s:7:\"boolean\";}}s:8:\"required\";a:2:{i:0;s:7:\"success\";i:1;s:4:\"data\";}s:5:\"title\";s:23:\"Default
  response object\";s:4:\"type\";s:6:\"object\";}s:10:\"Supervisor\";O:8:\"stdClass\":3:{s:5:\"allOf\";a:1:{i:0;O:8:\"stdClass\":1:{s:4:\"$ref\";s:23:\"#/definitions/Attribute\";}}s:10:\"properties\";O:8:\"stdClass\":1:{s:5:\"value\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:22:\"#/definitions/Employee\";}}s:4:\"type\";s:6:\"object\";}}"
...
