---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":11:{s:11:\"description\";s:102:\"Use these REST
  APIs to get the analytics reports associated with your Azure API Management deployment.\";s:5:\"title\";s:19:\"ApiManagementClient\";s:7:\"version\";s:10:\"2018-01-01\";s:21:\"x-apisguru-categories\";a:1:{i:0;s:5:\"cloud\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:131:\"https://api.apis.guru/v2/cache/logo/https_assets.onestore.ms_cdnfiles_onestorerolling-1606-01000_shell_v3_images_logo_microsoft.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":3:{s:6:\"format\";s:7:\"swagger\";s:3:\"url\";s:172:\"https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-01-01/apimreports.json\";s:7:\"version\";s:3:\"2.0\";}}s:11:\"x-preferred\";b:1;s:14:\"x-providerName\";s:9:\"azure.com\";s:13:\"x-serviceName\";s:25:\"apimanagement-apimreports\";s:6:\"x-tags\";a:2:{i:0;s:5:\"Azure\";i:1;s:9:\"Microsoft\";}s:10:\"x-datafire\";O:8:\"stdClass\":2:{s:4:\"name\";s:31:\"azure_apimanagement_apimreports\";s:4:\"type\";s:7:\"openapi\";}}"
host: management.azure.com
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/byApi
  : get:
      description: Lists report records by API.
      operationId: Reports_ListByApi
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: true
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/ReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsByApi:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 2
                nextLink: ""
                value:
                - apiId: /apis/5600b59475ff190048040001
                  apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: Echo API
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
                - apiId: /apis/57a03a13e4bbd5119c8b19e9
                  apiTimeAvg: 1015.760792
                  apiTimeMax: 1819.217300
                  apiTimeMin: 330.320600
                  bandwidth: 11019
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 1
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 13
                  callCountTotal: 14
                  name: httpbin
                  serviceTimeAvg: 957.094777
                  serviceTimeMax: 1697.361200
                  serviceTimeMin: 215.240000
      x-ms-odata: '#/definitions/ReportRecordContract'
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/byGeo
  : get:
      description: Lists report records by GeoGraphy.
      operationId: Reports_ListByGeo
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: false
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/ReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsByGeo:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 1
                nextLink: ""
                value:
                - apiTimeAvg: 1015.760792
                  apiTimeMax: 1819.217300
                  apiTimeMin: 330.320600
                  bandwidth: 11019
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 1
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 13
                  callCountTotal: 14
                  country: US
                  region: WA
                  serviceTimeAvg: 957.094777
                  serviceTimeMax: 1697.361200
                  serviceTimeMin: 215.240000
                  zip: "98052"
      x-ms-odata: '#/definitions/ReportRecordContract'
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/byOperation
  : get:
      description: Lists report records by API Operations.
      operationId: Reports_ListByOperation
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: true
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/ReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsByOperation:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 3
                nextLink: ""
                value:
                - apiId: /apis/57a03a13e4bbd5119c8b19e9
                  apiTimeAvg: 1015.760792
                  apiTimeMax: 1819.217300
                  apiTimeMin: 330.320600
                  bandwidth: 11019
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 1
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 13
                  callCountTotal: 14
                  name: get
                  operationId: /apis/57a03a13e4bbd5119c8b19e9/operations/57a03a1dd8d14f0a780d7d14
                  serviceTimeAvg: 957.094777
                  serviceTimeMax: 1697.361200
                  serviceTimeMin: 215.240000
                - apiId: /apis/57c999d1e4bbd50c988cb2c3
                  apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: GetWeatherInformation
                  operationId: /apis/57c999d1e4bbd50c988cb2c3/operations/57c999d1e4bbd50df889c93e
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
                - apiId: /apis/57c999d1e4bbd50c988cb2c3
                  apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: GetCityForecastByZIP
                  operationId: /apis/57c999d1e4bbd50c988cb2c3/operations/57c999d1e4bbd50df889c93f
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
      x-ms-odata: '#/definitions/ReportRecordContract'
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/byProduct
  : get:
      description: Lists report records by Product.
      operationId: Reports_ListByProduct
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: true
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/ReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsByProduct:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 2
                nextLink: ""
                value:
                - apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: Starter
                  productId: /products/5600b59475ff190048060001
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
                - apiTimeAvg: 1015.760792
                  apiTimeMax: 1819.217300
                  apiTimeMin: 330.320600
                  bandwidth: 11019
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 1
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 13
                  callCountTotal: 14
                  name: Unlimited
                  productId: /products/5600b59475ff190048060002
                  serviceTimeAvg: 957.094777
                  serviceTimeMax: 1697.361200
                  serviceTimeMin: 215.240000
      x-ms-odata: '#/definitions/ReportRecordContract'
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/byRequest
  : get:
      description: Lists report records by Request.
      operationId: Reports_ListByRequest
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: true
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/RequestReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsByRequest:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 2
                value:
                - apiId: /apis/5931a75ae4bbd512a88c680b
                  apiRegion: East Asia
                  apiTime: 221.154400
                  cache: none
                  ipAddress: 207.xx.155.xx
                  method: GET
                  operationId: /apis/5931a75ae4bbd512a88c680b/operations/-
                  productId: /products/-
                  requestId: 63e7119c-26aa-433c-96d7-f6f3267ff52f
                  requestSize: 0
                  responseCode: 404
                  responseSize: 405
                  serviceTime: 0
                  subscriptionId: /subscriptions/5600b59475ff190048070002
                  timestamp: "2017-06-03T00:17:00.1649134Z"
                  url: https://apimService1.azure-api.net/echo/resource?param1=sample
                  userId: /users/1
                - apiId: /apis/5931a75ae4bbd512a88c680b
                  apiRegion: East Asia
                  apiTime: 6.675400
                  cache: none
                  ipAddress: 207.xx.155.xx
                  method: POST
                  operationId: /apis/5931a75ae4bbd512a88c680b/operations/-
                  productId: /products/-
                  requestId: e581b7f7-c9ec-4fc6-8ab9-3855d9b00b04
                  requestSize: 0
                  responseCode: 404
                  responseSize: 403
                  serviceTime: 0
                  subscriptionId: /subscriptions/5600b59475ff190048070002
                  timestamp: "2017-06-03T00:17:20.5255131Z"
                  url: https://apimService1.azure-api.net/echo/resource
                  userId: /users/1
      x-ms-odata: '#/definitions/RequestReportRecordContract'
      x-ms-pageable: []
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/bySubscription
  : get:
      description: Lists report records by subscription.
      operationId: Reports_ListBySubscription
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: false
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/ReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsBySubscription:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 3
                nextLink: ""
                value:
                - apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: ""
                  productId: /products/5600b59475ff190048060001
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
                  subscriptionId: /subscriptions/5600b59475ff190048070001
                  userId: /users/1
                - apiTimeAvg: 1015.760792
                  apiTimeMax: 1819.217300
                  apiTimeMin: 330.320600
                  bandwidth: 11019
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 1
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 13
                  callCountTotal: 14
                  name: ""
                  productId: /products/5600b59475ff190048060002
                  serviceTimeAvg: 957.094777
                  serviceTimeMax: 1697.361200
                  serviceTimeMin: 215.240000
                  subscriptionId: /subscriptions/5600b59475ff190048070002
                  userId: /users/1
                - apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: ""
                  productId: /products/5702e97e5157a50f48dce801
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
                  subscriptionId: /subscriptions/5702e97e5157a50a9c733303
                  userId: /users/1
      x-ms-odata: '#/definitions/ReportRecordContract'
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/byTime
  : get:
      description: Lists report records by Time.
      operationId: Reports_ListByTime
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: false
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: 'By time interval. Interval must be multiple of 15 minutes and
          may not be zero. The value should be in ISO  8601 format (http://en.wikipedia.org/wiki/ISO_8601#Durations).This
          code can be used to convert TimeSpan to a valid interval string: XmlConvert.ToString(new
          TimeSpan(hours, minutes, secconds))'
        format: duration
        in: query
        name: interval
        required: true
        type: string
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/ReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsByTime:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            interval: PT15M
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 2
                nextLink: ""
                value:
                - apiTimeAvg: 1337.463350
                  apiTimeMax: 1819.217300
                  apiTimeMin: 885.083900
                  bandwidth: 3243
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 4
                  callCountTotal: 4
                  interval: PT15M
                  serviceTimeAvg: 1255.917425
                  serviceTimeMax: 1697.361200
                  serviceTimeMin: 882.826400
                  timestamp: "2017-06-03T00:15:00Z"
                - apiTimeAvg: 872.781878
                  apiTimeMax: 1093.840700
                  apiTimeMin: 330.320600
                  bandwidth: 7776
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 1
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 9
                  callCountTotal: 10
                  interval: PT15M
                  serviceTimeAvg: 824.284711
                  serviceTimeMax: 973.226200
                  serviceTimeMin: 215.240000
                  timestamp: "2017-06-03T00:30:00Z"
      x-ms-odata: '#/definitions/ReportRecordContract'
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/byUser
  : get:
      description: Lists report records by User.
      operationId: Reports_ListByUser
      parameters:
      - description: The name of the resource group.
        in: path
        name: resourceGroupName
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The name of the API Management service.
        in: path
        maxLength: 50
        minLength: 1
        name: serviceName
        pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        required: true
        type: string
        x-ms-parameter-location: method
      - description: The filter to apply on the operation.
        in: query
        name: $filter
        required: true
        type: string
      - description: Number of records to return.
        format: int32
        in: query
        minimum: 1
        name: $top
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Number of records to skip.
        format: int32
        in: query
        minimum: 0
        name: $skip
        required: false
        type: integer
        x-ms-parameter-location: method
      - description: Version of the API to be used with the client request.
        in: query
        name: api-version
        required: true
        type: string
      - description: Subscription credentials which uniquely identify Microsoft Azure
          subscription. The subscription ID forms part of the URI for every service
          call.
        in: path
        name: subscriptionId
        required: true
        type: string
      responses:
        200:
          description: Lists a collection of Report record.
          schema:
            $ref: '#/definitions/ReportCollection'
      tags:
      - Reports
      x-ms-examples:
        ApiManagementGetReportsByUser:
          parameters:
            $filter: timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'
            api-version: "2018-01-01"
            resourceGroupName: rg1
            serviceName: apimService1
            subscriptionId: subid
          responses:
            200:
              body:
                count: 3
                nextLink: ""
                value:
                - apiTimeAvg: 1015.760792
                  apiTimeMax: 1819.217300
                  apiTimeMin: 330.320600
                  bandwidth: 11019
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 1
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 13
                  callCountTotal: 14
                  name: Administrator
                  serviceTimeAvg: 957.094777
                  serviceTimeMax: 1697.361200
                  serviceTimeMin: 215.240000
                  userId: /users/1
                - apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: Samir Solanki
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
                  userId: /users/56eaec62baf08b06e46d27fd
                - apiTimeAvg: 0
                  apiTimeMax: 0
                  apiTimeMin: 0
                  bandwidth: 0
                  cacheHitCount: 0
                  cacheMissCount: 0
                  callCountBlocked: 0
                  callCountFailed: 0
                  callCountOther: 0
                  callCountSuccess: 0
                  callCountTotal: 0
                  name: Anonymous
                  serviceTimeAvg: 0
                  serviceTimeMax: 0
                  serviceTimeMin: 0
                  userId: /users/54c800b332965a0035030000
      x-ms-odata: '#/definitions/ReportRecordContract'
      x-ms-pageable:
        nextLinkName: nextLink
produces:
- application/json
schemes:
- https
definitions: !php/object "O:8:\"stdClass\":4:{s:16:\"ReportCollection\";O:8:\"stdClass\":2:{s:11:\"description\";s:41:\"Paged
  Report records list representation.\";s:10:\"properties\";O:8:\"stdClass\":3:{s:5:\"count\";O:8:\"stdClass\":3:{s:11:\"description\";s:43:\"Total
  record count number across all pages.\";s:6:\"format\";s:5:\"int64\";s:4:\"type\";s:7:\"integer\";}s:8:\"nextLink\";O:8:\"stdClass\":2:{s:11:\"description\";s:22:\"Next
  page link if any.\";s:4:\"type\";s:6:\"string\";}s:5:\"value\";O:8:\"stdClass\":3:{s:11:\"description\";s:12:\"Page
  values.\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:34:\"#/definitions/ReportRecordContract\";}s:4:\"type\";s:5:\"array\";}}}s:20:\"ReportRecordContract\";O:8:\"stdClass\":2:{s:11:\"description\";s:12:\"Report
  data.\";s:10:\"properties\";O:8:\"stdClass\":26:{s:5:\"apiId\";O:8:\"stdClass\":2:{s:11:\"description\";s:34:\"API
  identifier path. /apis/{apiId}\";s:4:\"type\";s:6:\"string\";}s:9:\"apiRegion\";O:8:\"stdClass\":2:{s:11:\"description\";s:22:\"API
  region identifier.\";s:4:\"type\";s:6:\"string\";}s:10:\"apiTimeAvg\";O:8:\"stdClass\":3:{s:11:\"description\";s:40:\"Average
  time it took to process request.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:10:\"apiTimeMax\";O:8:\"stdClass\":3:{s:11:\"description\";s:40:\"Maximum
  time it took to process request.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:10:\"apiTimeMin\";O:8:\"stdClass\":3:{s:11:\"description\";s:40:\"Minimum
  time it took to process request.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:9:\"bandwidth\";O:8:\"stdClass\":3:{s:11:\"description\";s:19:\"Bandwidth
  consumed.\";s:6:\"format\";s:5:\"int64\";s:4:\"type\";s:7:\"integer\";}s:13:\"cacheHitCount\";O:8:\"stdClass\":3:{s:11:\"description\";s:58:\"Number
  of times when content was served from cache policy.\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:14:\"cacheMissCount\";O:8:\"stdClass\":3:{s:11:\"description\";s:49:\"Number
  of times content was fetched from backend.\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:16:\"callCountBlocked\";O:8:\"stdClass\":3:{s:11:\"description\";s:172:\"Number
  of calls blocked due to invalid credentials. This includes calls returning HttpStatusCode.Unauthorize
  and HttpStatusCode.Forbidden and HttpStatusCode.TooManyRequests\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:15:\"callCountFailed\";O:8:\"stdClass\":3:{s:11:\"description\";s:185:\"Number
  of calls failed due to proxy or backend errors. This includes calls returning HttpStatusCode.BadRequest(400)
  and any Code between HttpStatusCode.InternalServerError (500) and 600\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:14:\"callCountOther\";O:8:\"stdClass\":3:{s:11:\"description\";s:22:\"Number
  of other calls.\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:16:\"callCountSuccess\";O:8:\"stdClass\":3:{s:11:\"description\";s:146:\"Number
  of succesful calls. This includes calls returning HttpStatusCode <= 301 and HttpStatusCode.NotModified
  and HttpStatusCode.TemporaryRedirect\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:14:\"callCountTotal\";O:8:\"stdClass\":3:{s:11:\"description\";s:22:\"Total
  number of calls.\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:7:\"country\";O:8:\"stdClass\":2:{s:11:\"description\";s:45:\"Country
  to which this record data is related.\";s:4:\"type\";s:6:\"string\";}s:8:\"interval\";O:8:\"stdClass\":2:{s:11:\"description\";s:180:\"Length
  of agregation period.  Interval must be multiple of 15 minutes and may not be zero.
  The value should be in ISO 8601 format (http://en.wikipedia.org/wiki/ISO_8601#Durations).\";s:4:\"type\";s:6:\"string\";}s:4:\"name\";O:8:\"stdClass\":2:{s:11:\"description\";s:86:\"Name
  depending on report endpoint specifies product, API, operation or developer name.\";s:4:\"type\";s:6:\"string\";}s:11:\"operationId\";O:8:\"stdClass\":2:{s:11:\"description\";s:65:\"Operation
  identifier path. /apis/{apiId}/operations/{operationId}\";s:4:\"type\";s:6:\"string\";}s:9:\"productId\";O:8:\"stdClass\":3:{s:11:\"description\";s:46:\"Product
  identifier path. /products/{productId}\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:6:\"region\";O:8:\"stdClass\":2:{s:11:\"description\";s:52:\"Country
  region to which this record data is related.\";s:4:\"type\";s:6:\"string\";}s:14:\"serviceTimeAvg\";O:8:\"stdClass\":3:{s:11:\"description\";s:51:\"Average
  time it took to process request on backend.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:14:\"serviceTimeMax\";O:8:\"stdClass\":3:{s:11:\"description\";s:51:\"Maximum
  time it took to process request on backend.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:14:\"serviceTimeMin\";O:8:\"stdClass\":3:{s:11:\"description\";s:51:\"Minimum
  time it took to process request on backend.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:14:\"subscriptionId\";O:8:\"stdClass\":2:{s:11:\"description\";s:61:\"Subscription
  identifier path. /subscriptions/{subscriptionId}\";s:4:\"type\";s:6:\"string\";}s:9:\"timestamp\";O:8:\"stdClass\":3:{s:11:\"description\";s:134:\"Start
  of aggregation period. The date conforms to the following format: `yyyy-MM-ddTHH:mm:ssZ`
  as specified by the ISO 8601 standard.\n\";s:6:\"format\";s:9:\"date-time\";s:4:\"type\";s:6:\"string\";}s:6:\"userId\";O:8:\"stdClass\":3:{s:11:\"description\";s:37:\"User
  identifier path. /users/{userId}\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:3:\"zip\";O:8:\"stdClass\":2:{s:11:\"description\";s:46:\"Zip
  code to which this record data is related.\";s:4:\"type\";s:6:\"string\";}}}s:23:\"RequestReportCollection\";O:8:\"stdClass\":2:{s:11:\"description\";s:41:\"Paged
  Report records list representation.\";s:10:\"properties\";O:8:\"stdClass\":2:{s:5:\"count\";O:8:\"stdClass\":3:{s:11:\"description\";s:43:\"Total
  record count number across all pages.\";s:6:\"format\";s:5:\"int64\";s:4:\"type\";s:7:\"integer\";}s:5:\"value\";O:8:\"stdClass\":3:{s:11:\"description\";s:12:\"Page
  values.\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:41:\"#/definitions/RequestReportRecordContract\";}s:4:\"type\";s:5:\"array\";}}}s:27:\"RequestReportRecordContract\";O:8:\"stdClass\":2:{s:11:\"description\";s:20:\"Request
  Report data.\";s:10:\"properties\";O:8:\"stdClass\":18:{s:5:\"apiId\";O:8:\"stdClass\":2:{s:11:\"description\";s:34:\"API
  identifier path. /apis/{apiId}\";s:4:\"type\";s:6:\"string\";}s:9:\"apiRegion\";O:8:\"stdClass\":2:{s:11:\"description\";s:70:\"Azure
  region where the gateway that processed this request is located.\";s:4:\"type\";s:6:\"string\";}s:7:\"apiTime\";O:8:\"stdClass\":3:{s:11:\"description\";s:47:\"The
  total time it took to process this request.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:19:\"backendResponseCode\";O:8:\"stdClass\":2:{s:11:\"description\";s:99:\"The
  HTTP status code received by the gateway as a result of forwarding this request
  to the backend.\";s:4:\"type\";s:6:\"string\";}s:5:\"cache\";O:8:\"stdClass\":2:{s:11:\"description\";s:279:\"Specifies
  if response cache was involved in generating the response. If the value is none,
  the cache was not used. If the value is hit, cached response was returned. If the
  value is miss, the cache was used but lookup resulted in a miss and request was
  fullfilled by the backend.\";s:4:\"type\";s:6:\"string\";}s:9:\"ipAddress\";O:8:\"stdClass\":2:{s:11:\"description\";s:51:\"The
  client IP address associated with this request.\";s:4:\"type\";s:6:\"string\";}s:6:\"method\";O:8:\"stdClass\":2:{s:11:\"description\";s:46:\"The
  HTTP method associated with this request..\";s:4:\"type\";s:6:\"string\";}s:11:\"operationId\";O:8:\"stdClass\":2:{s:11:\"description\";s:65:\"Operation
  identifier path. /apis/{apiId}/operations/{operationId}\";s:4:\"type\";s:6:\"string\";}s:9:\"productId\";O:8:\"stdClass\":3:{s:11:\"description\";s:46:\"Product
  identifier path. /products/{productId}\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:9:\"requestId\";O:8:\"stdClass\":2:{s:11:\"description\";s:19:\"Request
  Identifier.\";s:4:\"type\";s:6:\"string\";}s:11:\"requestSize\";O:8:\"stdClass\":3:{s:11:\"description\";s:26:\"The
  size of this request..\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:12:\"responseCode\";O:8:\"stdClass\":3:{s:11:\"description\";s:45:\"The
  HTTP status code returned by the gateway.\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:12:\"responseSize\";O:8:\"stdClass\":3:{s:11:\"description\";s:49:\"The
  size of the response returned by the gateway.\";s:6:\"format\";s:5:\"int32\";s:4:\"type\";s:7:\"integer\";}s:11:\"serviceTime\";O:8:\"stdClass\":3:{s:11:\"description\";s:81:\"he
  time it took to forward this request to the backend and get the response back.\";s:6:\"format\";s:6:\"double\";s:4:\"type\";s:6:\"number\";}s:14:\"subscriptionId\";O:8:\"stdClass\":2:{s:11:\"description\";s:61:\"Subscription
  identifier path. /subscriptions/{subscriptionId}\";s:4:\"type\";s:6:\"string\";}s:9:\"timestamp\";O:8:\"stdClass\":3:{s:11:\"description\";s:83:\"The
  date and time when this request was received by the gateway in ISO 8601 format.\";s:6:\"format\";s:9:\"date-time\";s:4:\"type\";s:6:\"string\";}s:3:\"url\";O:8:\"stdClass\":2:{s:11:\"description\";s:42:\"The
  full URL associated with this request.\";s:4:\"type\";s:6:\"string\";}s:6:\"userId\";O:8:\"stdClass\":3:{s:11:\"description\";s:37:\"User
  identifier path. /users/{userId}\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}}}}"
...
