---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":11:{s:11:\"description\";s:180:\"Provides create,
  read, update and delete functionality for Azure SQL Database resources including
  servers, databases, elastic pools, recommendations, operations, and usage metrics.\";s:5:\"title\";s:18:\"Azure
  SQL Database\";s:7:\"version\";s:10:\"2014-04-01\";s:21:\"x-apisguru-categories\";a:1:{i:0;s:5:\"cloud\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:131:\"https://api.apis.guru/v2/cache/logo/https_assets.onestore.ms_cdnfiles_onestorerolling-1606-01000_shell_v3_images_logo_microsoft.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":3:{s:6:\"format\";s:7:\"swagger\";s:3:\"url\";s:147:\"https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/metrics.json\";s:7:\"version\";s:3:\"2.0\";}}s:11:\"x-preferred\";b:1;s:14:\"x-providerName\";s:9:\"azure.com\";s:13:\"x-serviceName\";s:11:\"sql-metrics\";s:6:\"x-tags\";a:2:{i:0;s:5:\"Azure\";i:1;s:9:\"Microsoft\";}s:10:\"x-datafire\";O:8:\"stdClass\":2:{s:4:\"name\";s:17:\"azure_sql_metrics\";s:4:\"type\";s:7:\"openapi\";}}"
host: management.azure.com
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/metricDefinitions
  : get:
      description: Returns database metric definitions.
      operationId: Databases_ListMetricDefinitions
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - $ref: '#/parameters/ServerNameParameter'
      - description: The name of the database.
        in: path
        name: databaseName
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/MetricDefinitionListResult'
      tags:
      - Databases
      x-ms-examples:
        List database usage metrics:
          parameters:
            $filter: name/value eq 'cpu_percent' and timeGrain eq '00:10:00' and startTime
              eq '2017-06-2T18:35:00Z' and endTime eq '2017-06-2T18:55:00Z'
            api-version: "2014-04-01"
            databaseName: "3481"
            resourceGroupName: sqlcrudtest-6730
            serverName: sqlcrudtest-9007
            subscriptionId: 00000000-1111-2222-3333-444444444444
          responses:
            200:
              body:
                value:
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: CPU percentage
                    value: cpu_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Data IO percentage
                    value: physical_data_read_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Log IO percentage
                    value: log_write_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: DTU percentage
                    value: dtu_consumption_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Total database size
                    value: storage
                  primaryAggregationType: Maximum
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Bytes
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: In-Memory OLTP storage percent
                    value: xtp_storage_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Workers percentage
                    value: workers_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Sessions percentage
                    value: sessions_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: DTU limit
                    value: dtu_limit
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: DTU used
                    value: dtu_used
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Successful Connections
                    value: connection_successful
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Failed Connections
                    value: connection_failed
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Blocked by Firewall
                    value: blocked_by_firewall
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Deadlocks
                    value: deadlock
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Database size percentage
                    value: storage_percent
                  primaryAggregationType: Maximum
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
      x-ms-pageable: []
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/metrics
  : get:
      description: Returns database metrics.
      operationId: Databases_ListMetrics
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - $ref: '#/parameters/ServerNameParameter'
      - description: The name of the database.
        in: path
        name: databaseName
        required: true
        type: string
      - description: An OData filter expression that describes a subset of metrics
          to return.
        in: query
        name: $filter
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/MetricListResult'
      tags:
      - Databases
      x-ms-examples:
        List database usage metrics:
          parameters:
            $filter: name/value eq 'cpu_percent' and timeGrain eq '00:10:00' and startTime
              eq '2017-06-02T18:35:00Z' and endTime eq '2017-06-02T18:55:00Z'
            api-version: "2014-04-01"
            databaseName: "3481"
            resourceGroupName: sqlcrudtest-6730
            serverName: sqlcrudtest-9007
            subscriptionId: 00000000-1111-2222-3333-444444444444
          responses:
            200:
              body:
                value:
                - endTime: "2017-06-02T18:55:00Z"
                  metricValues:
                  - average: 0
                    count: 1
                    maximum: 0
                    minimum: 0
                    timestamp: "2017-06-02T18:30:01Z"
                    total: 0
                  - average: 0
                    count: 1
                    maximum: 0
                    minimum: 0
                    timestamp: "2017-06-02T18:40:01Z"
                    total: 0
                  - average: 0
                    count: 1
                    maximum: 0
                    minimum: 0
                    timestamp: "2017-06-02T18:50:01Z"
                    total: 0
                  name:
                    localizedValue: CPU percentage
                    value: cpu_percent
                  startTime: "2017-06-02T18:35:00Z"
                  timeGrain: 00:10:00
                  unit: percent
      x-ms-pageable: []
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/elasticPools/{elasticPoolName}/metricDefinitions
  : get:
      description: Returns elastic pool metric definitions.
      operationId: ElasticPools_ListMetricDefinitions
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - $ref: '#/parameters/ServerNameParameter'
      - description: The name of the elastic pool.
        in: path
        name: elasticPoolName
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/MetricDefinitionListResult'
      tags:
      - ElasticPools
      x-ms-examples:
        List database usage metrics:
          parameters:
            $filter: name/value eq 'cpu_percent' and timeGrain eq '00:10:00' and startTime
              eq '2017-06-2T18:35:00Z' and endTime eq '2017-06-2T18:55:00Z'
            api-version: "2014-04-01"
            elasticPoolName: "3481"
            resourceGroupName: sqlcrudtest-6730
            serverName: sqlcrudtest-9007
            subscriptionId: 00000000-1111-2222-3333-444444444444
          responses:
            200:
              body:
                value:
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: CPU percentage
                    value: cpu_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Data IO percentage
                    value: physical_data_read_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Log IO percentage
                    value: log_write_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: DTU percentage
                    value: dtu_consumption_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Total database size
                    value: storage
                  primaryAggregationType: Maximum
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Bytes
                - metricAvailabilities:
                  - retention: PT1H
                    timeGrain: PT15S
                  - retention: PT1H
                    timeGrain: PT60S
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: In-Memory OLTP storage percent
                    value: xtp_storage_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Workers percentage
                    value: workers_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Sessions percentage
                    value: sessions_percent
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: DTU limit
                    value: dtu_limit
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: DTU used
                    value: dtu_used
                  primaryAggregationType: Average
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Successful Connections
                    value: connection_successful
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Failed Connections
                    value: connection_failed
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Blocked by Firewall
                    value: blocked_by_firewall
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Deadlocks
                    value: deadlock
                  primaryAggregationType: Total
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Count
                - metricAvailabilities:
                  - retention: P14D
                    timeGrain: PT5M
                  - retention: P14D
                    timeGrain: PT1H
                  - retention: P14D
                    timeGrain: P1D
                  name:
                    localizedValue: Database size percentage
                    value: storage_percent
                  primaryAggregationType: Maximum
                  resourceUri: /subscriptions/b6a6e0c5-e79c-4c6d-a878-72eafbca4cf2/resourceGroups/QA/providers/Microsoft.Sql/servers/nafantest/databases/db1
                  unit: Percent
      x-ms-pageable: []
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/elasticPools/{elasticPoolName}/metrics
  : get:
      description: Returns elastic pool  metrics.
      operationId: ElasticPools_ListMetrics
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - $ref: '#/parameters/ServerNameParameter'
      - description: The name of the elastic pool.
        in: path
        name: elasticPoolName
        required: true
        type: string
      - description: An OData filter expression that describes a subset of metrics
          to return.
        in: query
        name: $filter
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/MetricListResult'
      tags:
      - ElasticPools
      x-ms-examples:
        List database usage metrics:
          parameters:
            $filter: name/value eq 'cpu_percent' and timeGrain eq '00:10:00' and startTime
              eq '2017-06-02T18:35:00Z' and endTime eq '2017-06-02T18:55:00Z'
            api-version: "2014-04-01"
            elasticPoolName: "3481"
            resourceGroupName: sqlcrudtest-6730
            serverName: sqlcrudtest-9007
            subscriptionId: 00000000-1111-2222-3333-444444444444
          responses:
            200:
              body:
                value:
                - endTime: "2017-06-02T18:55:00Z"
                  metricValues:
                  - average: 0
                    count: 1
                    maximum: 0
                    minimum: 0
                    timestamp: "2017-06-02T18:30:01Z"
                    total: 0
                  - average: 0
                    count: 1
                    maximum: 0
                    minimum: 0
                    timestamp: "2017-06-02T18:40:01Z"
                    total: 0
                  - average: 0
                    count: 1
                    maximum: 0
                    minimum: 0
                    timestamp: "2017-06-02T18:50:01Z"
                    total: 0
                  name:
                    localizedValue: CPU percentage
                    value: cpu_percent
                  startTime: "2017-06-02T18:35:00Z"
                  timeGrain: 00:10:00
                  unit: percent
      x-ms-pageable: []
produces:
- application/json
schemes:
- https
definitions: !php/object "O:8:\"stdClass\":7:{s:6:\"Metric\";O:8:\"stdClass\":2:{s:11:\"description\";s:17:\"Database
  metrics.\";s:10:\"properties\";O:8:\"stdClass\":6:{s:7:\"endTime\";O:8:\"stdClass\":4:{s:11:\"description\";s:46:\"The
  end time for the metric (ISO-8601 format).\";s:6:\"format\";s:9:\"date-time\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:12:\"metricValues\";O:8:\"stdClass\":4:{s:11:\"description\";s:61:\"The
  metric values for the specified time window and timestep.\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:25:\"#/definitions/MetricValue\";}s:8:\"readOnly\";b:1;s:4:\"type\";s:5:\"array\";}s:4:\"name\";O:8:\"stdClass\":3:{s:4:\"$ref\";s:24:\"#/definitions/MetricName\";s:11:\"description\";s:36:\"The
  name information for the metric.\";s:8:\"readOnly\";b:1;}s:9:\"startTime\";O:8:\"stdClass\":4:{s:11:\"description\";s:48:\"The
  start time for the metric (ISO-8601 format).\";s:6:\"format\";s:9:\"date-time\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:9:\"timeGrain\";O:8:\"stdClass\":3:{s:11:\"description\";s:56:\"The
  time step to be used to summarize the metric values.\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:4:\"unit\";O:8:\"stdClass\":5:{s:11:\"description\";s:23:\"The
  unit of the metric.\";s:4:\"enum\";a:6:{i:0;s:5:\"count\";i:1;s:5:\"bytes\";i:2;s:7:\"seconds\";i:3;s:7:\"percent\";i:4;s:14:\"countPerSecond\";i:5;s:14:\"bytesPerSecond\";}s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";s:9:\"x-ms-enum\";O:8:\"stdClass\":2:{s:13:\"modelAsString\";b:1;s:4:\"name\";s:8:\"UnitType\";}}}}s:18:\"MetricAvailability\";O:8:\"stdClass\":2:{s:11:\"description\";s:28:\"A
  metric availability value.\";s:10:\"properties\";O:8:\"stdClass\":2:{s:9:\"retention\";O:8:\"stdClass\":3:{s:11:\"description\";s:48:\"The
  length of retention for the database metric.\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:9:\"timeGrain\";O:8:\"stdClass\":3:{s:11:\"description\";s:39:\"The
  granularity of the database metric.\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}}}s:16:\"MetricDefinition\";O:8:\"stdClass\":2:{s:11:\"description\";s:29:\"A
  database metric definition.\";s:10:\"properties\";O:8:\"stdClass\":5:{s:20:\"metricAvailabilities\";O:8:\"stdClass\":4:{s:11:\"description\";s:56:\"The
  list of database metric availabities for the metric.\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:32:\"#/definitions/MetricAvailability\";}s:8:\"readOnly\";b:1;s:4:\"type\";s:5:\"array\";}s:4:\"name\";O:8:\"stdClass\":3:{s:4:\"$ref\";s:24:\"#/definitions/MetricName\";s:11:\"description\";s:36:\"The
  name information for the metric.\";s:8:\"readOnly\";b:1;}s:22:\"primaryAggregationType\";O:8:\"stdClass\":5:{s:11:\"description\";s:70:\"The
  primary aggregation type defining how metric values are displayed.\";s:4:\"enum\";a:6:{i:0;s:4:\"None\";i:1;s:7:\"Average\";i:2;s:5:\"Count\";i:3;s:7:\"Minimum\";i:4;s:7:\"Maximum\";i:5;s:5:\"Total\";}s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";s:9:\"x-ms-enum\";O:8:\"stdClass\":2:{s:13:\"modelAsString\";b:1;s:4:\"name\";s:22:\"PrimaryAggregationType\";}}s:11:\"resourceUri\";O:8:\"stdClass\":3:{s:11:\"description\";s:33:\"The
  resource uri of the database.\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:4:\"unit\";O:8:\"stdClass\":5:{s:11:\"description\";s:23:\"The
  unit of the metric.\";s:4:\"enum\";a:6:{i:0;s:5:\"Count\";i:1;s:5:\"Bytes\";i:2;s:7:\"Seconds\";i:3;s:7:\"Percent\";i:4;s:14:\"CountPerSecond\";i:5;s:14:\"BytesPerSecond\";}s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";s:9:\"x-ms-enum\";O:8:\"stdClass\":2:{s:13:\"modelAsString\";b:1;s:4:\"name\";s:18:\"UnitDefinitionType\";}}}}s:26:\"MetricDefinitionListResult\";O:8:\"stdClass\":3:{s:11:\"description\";s:59:\"The
  response to a list database metric definitions request.\";s:10:\"properties\";O:8:\"stdClass\":1:{s:5:\"value\";O:8:\"stdClass\":3:{s:11:\"description\";s:48:\"The
  list of metric definitions for the database.\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:30:\"#/definitions/MetricDefinition\";}s:4:\"type\";s:5:\"array\";}}s:8:\"required\";a:1:{i:0;s:5:\"value\";}}s:16:\"MetricListResult\";O:8:\"stdClass\":3:{s:11:\"description\";s:48:\"The
  response to a list database metrics request.\";s:10:\"properties\";O:8:\"stdClass\":1:{s:5:\"value\";O:8:\"stdClass\":3:{s:11:\"description\";s:37:\"The
  list of metrics for the database.\";s:5:\"items\";O:8:\"stdClass\":1:{s:4:\"$ref\";s:20:\"#/definitions/Metric\";}s:4:\"type\";s:5:\"array\";}}s:8:\"required\";a:1:{i:0;s:5:\"value\";}}s:10:\"MetricName\";O:8:\"stdClass\":2:{s:11:\"description\";s:23:\"A
  database metric name.\";s:10:\"properties\";O:8:\"stdClass\":2:{s:14:\"localizedValue\";O:8:\"stdClass\":3:{s:11:\"description\";s:41:\"The
  friendly name of the database metric.\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:5:\"value\";O:8:\"stdClass\":3:{s:11:\"description\";s:32:\"The
  name of the database metric.\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}}}s:11:\"MetricValue\";O:8:\"stdClass\":2:{s:11:\"description\";s:28:\"Represents
  database metrics.\";s:10:\"properties\";O:8:\"stdClass\":6:{s:7:\"average\";O:8:\"stdClass\":4:{s:11:\"description\";s:32:\"The
  average value of the metric.\";s:6:\"format\";s:6:\"double\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"number\";}s:5:\"count\";O:8:\"stdClass\":4:{s:11:\"description\";s:36:\"The
  number of values for the metric.\";s:6:\"format\";s:5:\"int32\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"number\";}s:7:\"maximum\";O:8:\"stdClass\":4:{s:11:\"description\";s:28:\"The
  max value of the metric.\";s:6:\"format\";s:6:\"double\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"number\";}s:7:\"minimum\";O:8:\"stdClass\":4:{s:11:\"description\";s:28:\"The
  min value of the metric.\";s:6:\"format\";s:6:\"double\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"number\";}s:9:\"timestamp\";O:8:\"stdClass\":4:{s:11:\"description\";s:39:\"The
  metric timestamp (ISO-8601 format).\";s:6:\"format\";s:9:\"date-time\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"string\";}s:5:\"total\";O:8:\"stdClass\":4:{s:11:\"description\";s:30:\"The
  total value of the metric.\";s:6:\"format\";s:6:\"double\";s:8:\"readOnly\";b:1;s:4:\"type\";s:6:\"number\";}}}}"
...
